stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn ci:test
  only:
  - merge_requests

build:
  stage: build
  script:
    - yarn ci:build
  only:
  - master

deploy:
  stage: deploy
  variables:
    NODE_ENV: production
    HOST_NAME: c0d3.com
  script:
    - yarn ci:deploy
  environment:
    name: production
    url: https://c0d3.com
  only:
  - master

