image: node:10.14.1

stages:
  - deploy

deploy_production:
  stage: deploy
  variables:
    NODE_ENV: production
    HOST_NAME: c0d3.com
  script:
    - pm2 deploy ecosystem.config.js production setup
    - pm2 deploy ecosystem.config.js production update
  environment:
    name: production
    url: https://c0d3.com
  only:
  - master

