image: node:10.14.1

stages:
  - test
  - deploy

cache:
  key: use-same-cache-for-all-branches-and-jobs
  paths:
  - node_modules/

before_script:
  - yarn

test:
  stage: test
  variables:
    NODE_ENV: test
  script:
    - yarn lint
    - echo "pm2 start Server/app.js --name test"
    - echo "npx jest"
    - echo "yarn tf"
    - echo "pm2 delete test"
  only:
  - merge_requests

deploy_production:
  stage: deploy
  variables:
    NODE_ENV: production
    REACT_APP_SERVER_URL: https://c0d3.com
    HOST_NAME: c0d3.com
    CLIENT_URL: https://c0d3.com
  script:
    - rm -rf build
    - CI=false yarn build
    - mv build/index.html public/root.html && rm public/index.html
    - pm2 delete app || true
    - pm2 reload prod --update-env || pm2 start Server/app.js --name prod
  environment:
    name: production
    url: https://c0d3.com
  only:
  - master

