stages:
  - test
  - build
  - deploy

cache:
  key: use-same-cache-for-all-branches-and-jobs
  paths:
  - node_modules/

test:
  stage: test
  script:
    - yarn ci:test
  only:
  - merge_requests

build:
  stage: build
  script:
    - yarn ci:build
  only:
  - master

deploy:
  stage: deploy
  variables:
    NODE_ENV: production
    REACT_APP_SERVER_URL: https://c0d3.com
    HOST_NAME: c0d3.com
    CLIENT_URL: https://c0d3.com
  script:
    - yarn ci:deploy
  environment:
    name: production
    url: https://c0d3.com
  only:
  - master

