image: node:10.14.1

stages:
  - deploy

before_script:
  - yarn

deploy_production:
  stage: deploy
  variables:
    NODE_ENV: production
    REACT_APP_SERVER_URL: https://c0d3.com
    HOST_NAME: c0d3.com
    CLIENT_URL: https://c0d3.com
  script:
    - rm -rf build
    - CI=false yarn build
    - mv build/index.html public/root.html && rm public/index.html
    - pm2 reload all || pm2 start Server/app.js
  environment:
    name: production
    url: https://c0d3.com
  only:
  - master

